title: Lakshmi B
description: >
  <br><br>
  <a target="_blank" href="https://www.linkedin.com/in/lakshmibalan/"><img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white" /></a>&nbsp;&nbsp;&nbsp;&nbsp;
  <br>
  <a target="_blank" href="https://twitter.com/lakshmib24"><img src="https://img.shields.io/badge/twitter-%231DA1F2.svg?&style=for-the-badge&logo=twitter&logoColor=white" /></a>&nbsp;&nbsp;&nbsp;&nbsp;
  <br>
  <a href="mailto:lakshmibk09@gmail.com?subject=Hello%20Lakshmi,%20From%20Github"><img src="https://img.shields.io/badge/gmail-%23D14836.svg?&style=for-the-badge&logo=gmail&logoColor=white" /></a>&nbsp;&nbsp;&nbsp;&nbsp;
theme: jekyll-theme-minimal
